# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import websiteSofie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Stad')),
                ('street', models.CharField(blank=True, max_length=50, verbose_name='Straat')),
                ('house_number', models.CharField(blank=True, max_length=50, verbose_name='Huisnummer')),
                ('area_code', models.CharField(blank=True, max_length=50, verbose_name='Postcode')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Geboortedatum')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='GSM nummer')),
                ('telephone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefoonnummer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Naam')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Onderwerp')),
                ('text', models.TextField(verbose_name='Tekst')),
            ],
            options={
                'verbose_name': 'Contactformulieren',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naam')),
            ],
            options={
                'verbose_name_plural': 'Criteria voor vastgoed',
            },
        ),
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_disclaimer', models.TextField(verbose_name='Disclaimer tekst')),
            ],
            options={
                'verbose_name_plural': 'Mijn disclaimer',
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('name', models.CharField(max_length=80, verbose_name='Naam')),
            ],
            options={
                'verbose_name_plural': 'Geregistreerden voor Ebook',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=20, verbose_name='Adres')),
                ('house_number', models.IntegerField(default='1', verbose_name='Huisnummer')),
                ('bus_nummer', models.CharField(blank=True, max_length=20)),
                ('area_code', models.CharField(max_length=8, verbose_name='Postcode')),
                ('town', models.CharField(max_length=50, verbose_name='Gemeente')),
                ('provincie', models.CharField(choices=[('ANTWERPEN', 'Antwerpen'), ('OOST_VLAANDEREN', 'Oost-Vlaanderen'), ('WEST_VLAANDEREN', 'West-Vlaanderen'), ('LIMBURG', 'Limburg'), ('LUIK', 'Luik'), ('NAMEN', 'Namen'), ('VLAAMS_BRABANT', 'Vlaams-brabant'), ('WAALS_BRABANT', 'Waals-Brabant'), ('HENEGOUWEN', 'Henegouwen'), ('BRUSSEL', 'Brussel'), ('LUXEMBURG', 'Luxemburg')], default='ANTWERPEN', max_length=30, verbose_name='Provincie')),
                ('country', models.CharField(default='Belgie', max_length=50, verbose_name='Land')),
                ('hits', models.IntegerField(default='0', verbose_name='Hits')),
                ('sale', models.BooleanField(verbose_name='Te koop')),
                ('rent', models.BooleanField(verbose_name='Te huur')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Verkoopprijs')),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Verhuurprijs')),
                ('date_placed', models.DateField(default=django.utils.timezone.now, verbose_name='Datum geplaatst')),
                ('beschikbaarheid', models.CharField(choices=[('AVAILABLE', 'Beschikbaar voor site'), ('N_AVAILABLE', 'Niet beschikbaar voor site'), ('IS_VERKOCHT', 'Is verkocht'), ('IS_REFERENTIE', 'Is verkocht en referentie')], default='AVAILABLE', max_length=20, verbose_name='Beschikbaarheid')),
                ('bedrooms', models.IntegerField(default='1', verbose_name='Slaapkamers')),
                ('bathrooms', models.IntegerField(default='1', verbose_name='Badkamers')),
                ('bebouwing', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('HALFOPEN', 'Halfopen'), ('GESLOTEN', 'Gesloten')], max_length=30, verbose_name='Bebouwing')),
                ('type_estate', models.CharField(blank=True, choices=[('HUIS', 'Huis'), ('APPARTEMENT', 'Appartement'), ('GROND', 'Grond'), ('KAMER/KOT', 'Kamer/Kot'), ('ANDERE', 'Andere')], default='HUIS', max_length=50, verbose_name='Type vastgoed')),
                ('surface', models.CharField(default=' ', max_length=50, verbose_name='Oppervlakte')),
                ('habitable_surface', models.CharField(default=' ', max_length=50, verbose_name='Bewoonbare oppervlakte')),
                ('description', models.TextField(default='Geen beschrijving beschikbaar', verbose_name='Beschrijving')),
                ('referencenumber', models.CharField(default=' ', max_length=50, unique=True, verbose_name='Referentienummer')),
                ('indekijker', models.BooleanField(default=False, verbose_name='In de kijker')),
            ],
            options={
                'verbose_name_plural': 'Vastgoed',
            },
        ),
        migrations.CreateModel(
            name='Estate_Bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bought', models.DateField(verbose_name='Datum gekocht')),
                ('estate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteSofie.Estate', verbose_name='Vastgoed_ID')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gebruikers_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Estate_Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Waarde')),
                ('criteria_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteSofie.Criteria', verbose_name='Criteria_ID')),
                ('estate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteSofie.Estate', verbose_name='Vastgoed_ID')),
            ],
            options={
                'verbose_name_plural': 'Vastgoed criteria',
            },
        ),
        migrations.CreateModel(
            name='Estate_Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateField(verbose_name='Datum gevolgd')),
                ('estate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteSofie.Estate', verbose_name='Vastgoed_ID')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gebruikers_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Estate_Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteSofie.Estate', verbose_name='Vastgoed_ID')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gebruikers_ID')),
            ],
            options={
                'verbose_name': 'Vastgoed verkoper',
            },
        ),
        migrations.CreateModel(
            name='Estate_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateField(default=websiteSofie.models.get_current_date)),
                ('estate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteSofie.Estate')),
            ],
            options={
                'verbose_name_plural': 'Vastgoed status',
            },
        ),
        migrations.CreateModel(
            name='EstateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Afbeelding')),
                ('is_display', models.BooleanField(default=False, verbose_name='Hoofdafbeelding')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='websiteSofie.Estate', verbose_name='Vastgoed')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vraag', models.TextField(verbose_name='Vraag')),
                ('antwoord', models.TextField(verbose_name='Antwoord')),
            ],
            options={
                'verbose_name_plural': 'Advies',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naam')),
                ('image', models.ImageField(upload_to='partner/', verbose_name='Afbeelding')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Zichtbaar')),
                ('date_partnered', models.DateField(verbose_name='Datum gepartnerd')),
                ('description', models.TextField(default='description', verbose_name='Beschrijving')),
                ('level', models.IntegerField(verbose_name='Niveau')),
            ],
            options={
                'verbose_name_plural': 'Mijn partners',
            },
        ),
        migrations.CreateModel(
            name='Privacybeleid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_privacybeleid', models.TextField(verbose_name='Privacybeleid tekst')),
            ],
            options={
                'verbose_name_plural': 'Mijn privacybeleid',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Review tekst')),
                ('review_title', models.CharField(max_length=50, verbose_name='Review titel')),
                ('review_rating', models.IntegerField(default=0, verbose_name='Review beoordeling')),
                ('date', models.DateField(default=websiteSofie.models.get_current_date, verbose_name='Datum')),
                ('approved', models.BooleanField(default=False, verbose_name='Goedgekeurd')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gebruikers_ID')),
            ],
            options={
                'verbose_name_plural': 'Geschreven reviews',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
                ('date_placed', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(default='Geen beschrijving beschikbaar')),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Naam')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('is_Subscribed', models.BooleanField(default=True, verbose_name='Geabonneerd')),
            ],
            options={
                'verbose_name_plural': 'Geregistreerden voor nieuwsbrief',
            },
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteSofie.Role', verbose_name='Rol_ID')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gebruikers_ID')),
            ],
        ),
        migrations.AddField(
            model_name='estate_status',
            name='status_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteSofie.Status'),
        ),
    ]
